baseurl        = "https://lyrise.blog.omnius-labs.com/"
title          = "Lyrise"
languageCode   = "en-us"
theme          = "hello-friend"
paginate       = 10
hasCJKLanguage = true

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true
    [markup.highlight]
        codeFences = false
        guessSyntax = false

[params]
    dateform        = "2006/01/02"
    dateformShort   = "01/02"
    dateformNum     = "2006-01-02"
    dateformNumTime = "2006-01-02 15:04 -0700"

    # Subtitle for home
    homeSubtitle = ""

    # Set disableReadOtherPosts to true in order to hide the links to other posts.
    disableReadOtherPosts = false

    # Metadata mostly used in document's head
    description = ""
    keywords = "blog"
    images = [""]

    # Default theme "light" or "dark"
    defaultTheme = "dark"

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
    [languages.en]
        title = "Lyrise"
        subtitle = ""
        keywords = ""
        copyright = ""
        readOtherPosts = "Read other posts"

    [languages.en.params.logo]
        logoText = "Lyrise"
        logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

# And you can even create generic menu
[[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"
[[menu.main]]
    identifier = "abount"
    name       = "About"
    url        = "/about"
