baseURL = "https://lyrise.blog.omnius-labs.com/"
defaultContentLanguage = "ja"
theme = "LoveIt"
themesDir = "./themes/"
description = "My God, It's Full of Stars."
title = "Lyrise"
enableRobotsTXT = false
enableGitInfo = true
enableEmoji = true

[languages]
  [languages.ja]
    weight = 1
    languageCode = "ja"
    languageName = "Japanese"
    hasCJKLanguage = true
    paginate = 12
    googleAnalytics = "UA-104419086-2"
    copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."
    [languages.ja.menu]
      [[languages.ja.menu.main]]
        identifier = "posts"
        pre = ""
        post = ""
        name = "Posts"
        url = "/posts/"
        title = ""
        weight = 1
      [[languages.ja.menu.main]]
        identifier = "tags"
        pre = ""
        post = ""
        name = "Tags"
        url = "/tags/"
        title = ""
        weight = 2
      [[languages.ja.menu.main]]
        identifier = "categories"
        pre = ""
        post = ""
        name = "Categories"
        url = "/categories/"
        title = ""
        weight = 3
      [[languages.ja.menu.main]]
        identifier = "documentation"
        pre = ""
        post = ""
        name = "Docs"
        url = "/docs/"
        title = ""
        weight = 4
      [[languages.ja.menu.main]]
        identifier = "about"
        pre = ""
        post = ""
        name = "About"
        url = "/about/"
        title = ""
        weight = 5
      [[languages.ja.menu.main]]
        identifier = "github"
        pre = "<i class='fab fa-github fa-fw'></i>"
        post = ""
        name = ""
        url = "https://github.com/lyrise/blog"
        title = "GitHub"
        weight = 6
    [languages.ja.params]
      description = "About LoveIt Theme"
      keywords = ["Theme", "Hugo"]
      [languages.ja.params.app]
        title = "LoveIt"
        noFavicon = true
        svgFavicon = ""
        themeColor = "#ffffff"
        iconColor = "#5bbad5"
        tileColor = "#da532c"
      [languages.ja.params.search]
        enable = false
        type = "algolia"
        contentLength = 4000
        placeholder = ""
        maxResultLength = 10
        snippetLength = 30
        highlightTag = "em"
        absoluteURL = false
        [languages.ja.params.search.algolia]
          index = "index.ja"
          appID = ""
          searchKey = ""
      [languages.ja.params.home]
        rss = 10
        [languages.ja.params.home.profile]
          enable = true
          gravatarEmail = ""
          avatarURL = ""
          title = ""
          subtitle = "My God, It's Full of Stars."
          typeit = true
          social = true
          disclaimer = ""
        [languages.ja.params.home.posts]
          enable = true
          paginate = 6
      [languages.ja.params.social]
        GitHub = "lyrise"
        Linkedin = ""
        Twitter = "lyrise1984"
        Instagram = ""
        Facebook = ""
        Telegram = ""
        Medium = ""
        Gitlab = ""
        Youtubelegacy = ""
        Youtubecustom = ""
        Youtubechannel = ""
        Tumblr = ""
        Quora = ""
        Keybase = ""
        Pinterest = ""
        Reddit = ""
        Codepen = ""
        FreeCodeCamp = ""
        Bitbucket = ""
        Stackoverflow = ""
        Weibo = ""
        Odnoklassniki = ""
        VK = ""
        Flickr = ""
        Xing = ""
        Snapchat = ""
        Soundcloud = ""
        Spotify = ""
        Bandcamp = ""
        Paypal = ""
        Fivehundredpx = ""
        Mix = ""
        Goodreads = ""
        Lastfm = ""
        Foursquare = ""
        Hackernews = ""
        Kickstarter = ""
        Patreon = ""
        Steam = ""
        Twitch = ""
        Strava = ""
        Skype = ""
        Whatsapp = ""
        Zhihu = ""
        Douban = ""
        Angellist = ""
        Slidershare = ""
        Jsfiddle = ""
        Deviantart = ""
        Behance = ""
        Dribbble = ""
        Wordpress = ""
        Vine = ""
        Googlescholar = ""
        Researchgate = ""
        Thingiverse = ""
        Devto = ""
        Gitea = ""
        XMPP = ""
        Matrix = ""
        Bilibili = ""
        Email = "lyrise1984@gmail.com"
        RSS = true
        [languages.ja.params.social.Mastodon]
          id = ""
          prefix = ""

[params]
  version = "0.2.X"
  defaultTheme = "auto"
  gitRepo = "https://github.com/lyrise/blog"
  fingerprint = ""
  dateFormat = "2006-01-02"
  images = [""]
  [params.header]
    desktopMode = "fixed"
    mobileMode = "auto"
    [params.header.title]
      logo = ""
      name = "Lyrise"
      pre = ""
      post = ""
      typeit = false

  [params.footer]
    enable = true
    custom = ''
    hugo = true
    copyright = true
    author = true
    since = 2020
    icp = ""
    license= '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'

  [params.section]
    paginate = 20
    dateFormat = "01-02"
    rss = 10

  [params.list]
    paginate = 20
    dateFormat = "01-02"
    rss = 10

  [params.page]
    hiddenFromHomePage = true
    hiddenFromSearch = true
    twemoji = false
    lightgallery = false
    ruby = true
    fraction = true
    fontawesome = true
    linkToMarkdown = true
    rssFullText = false
    [params.page.toc]
      enable = true
      keepStatic = false
      auto = true
    [params.page.code]
      copy = true
      maxShownLines = 10
    [params.page.math]
      enable = false
      blockLeftDelimiter = ""
      blockRightDelimiter = ""
      inlineLeftDelimiter = ""
      inlineRightDelimiter = ""
      copyTex = true
      mhchem = true
    [params.page.mapbox]
      accessToken = ""
      lightStyle = "mapbox://styles/mapbox/light-v10?optimize=true"
      darkStyle = "mapbox://styles/mapbox/dark-v10?optimize=true"
      navigation = true
      geolocate = true
      scale = true
      fullscreen = true
    [params.page.share]
      enable = true
      Twitter = true
      Facebook = true
      Linkedin = false
      Whatsapp = false
      Pinterest = false
      Tumblr = false
      HackerNews = true
      Reddit = false
      VK = false
      Buffer = false
      Xing = false
      Line = true
      Instapaper = false
      Pocket = false
      Digg = false
      Stumbleupon = false
      Flipboard = false
      Weibo = true
      Renren = false
      Myspace = false
      Blogger = false
      Baidu = false
      Odnoklassniki = false
      Evernote = false
      Skype = false
      Trello = false
      Mix = false
    [params.page.comment]
      enable = false
      [params.page.comment.disqus]
        enable = false
        shortname = ""
      [params.page.comment.gitalk]
        enable = false
        owner = ""
        repo = ""
        clientId = ""
        clientSecret = ""
      [params.page.comment.valine]
        enable = false
        appId = ""
        appKey = ""
        placeholder = ""
        avatar = "mp"
        meta= ""
        pageSize = 10
        lang = ""
        visitor = true
        recordIP = true
        highlight = true
        enableQQ = false
        serverURLs = "https://leancloud.hugoloveit.com"
        emoji = ""
      [params.page.comment.facebook]
        enable = false
        width = "100%"
        numPosts = 10
        appId = ""
        languageCode = ""
      [params.page.comment.telegram]
        enable = false
        siteID = ""
        limit = 5
        height = ""
        color = ""
        colorful = true
        dislikes = false
        outlined = false
      [params.page.comment.commento]
        enable = false
      [params.page.comment.utterances]
        enable = false
        repo = ""
        issueTerm = "pathname"
        label = ""
        lightTheme = "github-light"
        darkTheme = "github-dark"
    [params.page.library]
      [params.page.library.css]
      [params.page.library.js]
    [params.page.seo]
      images = []
      [params.page.seo.publisher]
        name = ""
        logoUrl = ""

  [params.typeit]
    speed = 100
    cursorSpeed = 1000
    cursorChar = "|"
    duration = -1

  [params.verification]
    google = ""
    bing = ""
    yandex = ""
    pinterest = ""
    baidu = ""

  [params.seo]
    image = ""
    thumbnailUrl = ""
  
  [params.analytics]
    enable = false
    [params.analytics.google]
      id = ""
      anonymizeIP = true
    [params.analytics.fathom]
      id = ""
      server = ""

  [params.cookieconsent]
    enable = false
    [params.cookieconsent.content]
      message = ""
      dismiss = ""
      link = ""

  [params.cdn]
  [params.compatibility]
    polyfill = false
    objectFit = false

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.renderer]
      unsafe = true
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 6

[author]
  name = "Lyrise"
  email = ""
  link = ""

[sitemap]
  changefreq = ""
  filename = ""
  priority = 0.5

[Permalinks]
  posts = ":filename"

[privacy]
  [privacy.twitter]
    enableDNT = true
  [privacy.youtube]
    privacyEnhanced = true

[mediaTypes]
  [mediaTypes."text/plain"]
    suffixes = ["md"]

[outputFormats.MarkDown]
  mediaType = "text/plain"
  isPlainText = true
  isHTML = false

[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML", "MarkDown"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  taxonomyTerm = ["HTML"]
